project:
  type: website


website:
  title: "AI vs. Non-AI Job Growth:"
  site-url: "https://jackyman81.github.io/ad688-employability-sp65A1-group3/"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - href: research_introduction.qmd
        text: "Research"
      - href: data_analysis.ipynb
        text: "Data Analysis"
      - href: career_plan.qmd
        text: "Career Strategy"
format:
  html:
    theme: cosmo
    toc: true
